In [1]:
import numpy as np

In [3]:
#!pip install pandas

In [4]:
import pandas as pd

In [7]:
from numpy import *

## Numpy Arrays

### From List

In [8]:
v = array([1,2,3,4])

In [9]:
v

array([1, 2, 3, 4])

In [11]:
M = array([[1,2], [3, 4]])

In [12]:
M

array([[1, 2],
       [3, 4]])

In [13]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

In [14]:
v.shape

(4,)

In [15]:
M.shape

(2, 2)

In [16]:
M.size, v.size

(4, 4)

In [17]:
M.dtype

dtype('int32')

### from array generating function

In [18]:
x = arange(0, 10, 1)

In [19]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x = arange(-1, 1, 0.2)

In [21]:
x

array([-1.00000000e+00, -8.00000000e-01, -6.00000000e-01, -4.00000000e-01,
       -2.00000000e-01, -2.22044605e-16,  2.00000000e-01,  4.00000000e-01,
        6.00000000e-01,  8.00000000e-01])

In [22]:
random_array = random.rand(5,5)

In [24]:
random_array.size

25

In [25]:
random_array

array([[0.80629695, 0.99383353, 0.91427857, 0.47779199, 0.12413999],
       [0.27483235, 0.62930671, 0.03340017, 0.80144175, 0.32234558],
       [0.96095514, 0.73228198, 0.82698273, 0.50880843, 0.2012942 ],
       [0.26884613, 0.40421692, 0.49538678, 0.50010869, 0.68057514],
       [0.80344238, 0.68603015, 0.0681625 , 0.41891997, 0.36651293]])

In [26]:
diagonal_array = diag([1,2,3,4])

In [27]:
diagonal_array

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [29]:
zeros_array = zeros((3,3))

In [31]:
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
ones_array = ones((3,3))

In [32]:
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Data Frame menggunakan Pandas

In [35]:
products={
    "id":["001", "002"],
    "name":["Chocolate", "Shampoo"],
    "price": [20000, 10000]
}

In [36]:
df_products = pd.DataFrame(products)

In [37]:
df_products

id       name  price
0  001  Chocolate  20000
1  002    Shampoo  10000

In [38]:
df_products['sales'] = 10

In [39]:
df_products

id       name  price  sales
0  001  Chocolate  20000     10
1  002    Shampoo  10000     10

In [40]:
for idx, row in df_products.iterrows():
    print(idx, row['id'], row['name'], row['price'])

0 001 Chocolate 20000
1 002 Shampoo 10000


In [41]:
df_products.head(1)

id       name  price  sales
0  001  Chocolate  20000     10

In [42]:
df_products.tail(1)

id     name  price  sales
1  002  Shampoo  10000     10

In [43]:
df_products.name

0    Chocolate
1      Shampoo
Name: name, dtype: object

In [44]:
df_products.price

0    20000
1    10000
Name: price, dtype: int64

In [45]:
df_products[['name', 'price']]

name  price
0  Chocolate  20000
1    Shampoo  10000

In [46]:
df_products.loc[df_products['name'] == 'Chocolate']

id       name  price  sales
0  001  Chocolate  20000     10

## Matplotlib

In [48]:
x = np.linspace(0, 5, 10)

In [49]:
x

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [50]:
y = x ** 2

In [51]:
y

array([ 0.        ,  0.30864198,  1.2345679 ,  2.77777778,  4.9382716 ,
        7.71604938, 11.11111111, 15.12345679, 19.75308642, 25.        ])

In [54]:
#!pip install matplotlib

In [53]:
import matplotlib

ModuleNotFoundError: No module named 'matplotlib'

In [52]:
figure()
plot(x, y, 'r')
xlabel('x')
ylabel('y')

NameError: name 'figure' is not defined